In [1]:
import pandas as pd

In [14]:
df22 = pd.read_csv('movies.csv')
df22

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy
27275,131258,The Pirates (2014),Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror

In [7]:
!pip install html5lib

Requirement already satisfied: html5lib in c:\users\jangi\anaconda3\lib\site-packages (1.1)
Requirement already satisfied: webencodings in c:\users\jangi\anaconda3\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in c:\users\jangi\anaconda3\lib\site-packages (from html5lib) (1.16.0)

In [16]:
df22.shape

(27278, 3)

In [17]:
df22.columns

Index(['movieId', 'title', 'genres'], dtype='object')

In [24]:
 len(df22['genres'].unique())

1342

In [25]:
df22['genres'].value_counts()

Drama                                                  4520
Comedy                                                 2294
Documentary                                            1942
Comedy|Drama                                           1264
Drama|Romance                                          1075
                                                       ...
Action|Comedy|Crime|Western                               1
Action|Fantasy|Sci-Fi|Thriller                            1
Action|Drama|Fantasy|Horror|Mystery|Sci-Fi|Thriller       1
Action|Drama|Fantasy|Romance                              1
Animation|Children|Comedy|Western                         1
Name: genres, Length: 1342, dtype: int64

# DataFrame is a tool to analysis data and it is use in ML 
# dataframe is a mutable type

# New column addition

In [28]:
df22['test'] = 100

In [29]:
df22

,movieId,title,genres,test
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,100
1,2,Jumanji (1995),Adventure|Children|Fantasy,100
2,3,Grumpier Old Men (1995),Comedy|Romance,100
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,100
4,5,Father of the Bride Part II (1995),Comedy,100
...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,100
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,100
27275,131258,The Pirates (2014),Adventure,100
27276,131260,Rentun Ruusu (2001),(no genres listed),100
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,100

In [34]:
df22['title_genres']= df22['title']+df22['genres']
df22

,movieId,title,genres,test,title_genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,100,Toy Story (1995)Adventure|Animation|Children|C...
1,2,Jumanji (1995),Adventure|Children|Fantasy,100,Jumanji (1995)Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance,100,Grumpier Old Men (1995)Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,100,Waiting to Exhale (1995)Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy,100,Father of the Bride Part II (1995)Comedy
...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,100,Kein Bund für's Leben (2007)Comedy
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,100,"Feuer, Eis & Dosenbier (2002)Comedy"
27275,131258,The Pirates (2014),Adventure,100,The Pirates (2014)Adventure
27276,131260,Rentun Ruusu (2001),(no genres listed),100,Rentun Ruusu (2001)(no genres listed)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,100,Innocence (2014)Adventure|Fantasy|Horror

In [35]:
df22['new_movieid']= (df22['movieId']/100)*5
df22

,movieId,title,genres,test,title_genres,new_movieid
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,100,Toy Story (1995)Adventure|Animation|Children|C...,0.05
1,2,Jumanji (1995),Adventure|Children|Fantasy,100,Jumanji (1995)Adventure|Children|Fantasy,0.10
2,3,Grumpier Old Men (1995),Comedy|Romance,100,Grumpier Old Men (1995)Comedy|Romance,0.15
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,100,Waiting to Exhale (1995)Comedy|Drama|Romance,0.20
4,5,Father of the Bride Part II (1995),Comedy,100,Father of the Bride Part II (1995)Comedy,0.25
...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,100,Kein Bund für's Leben (2007)Comedy,6562.70
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,100,"Feuer, Eis & Dosenbier (2002)Comedy",6562.80
27275,131258,The Pirates (2014),Adventure,100,The Pirates (2014)Adventure,6562.90
27276,131260,Rentun Ruusu (2001),(no genres listed),100,Rentun Ruusu (2001)(no genres listed),6563.00
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,100,Innocence (2014)Adventure|Fantasy|Horror,6563.10

In [40]:
df22['title_len']=len(df22['title'])
df22

,movieId,title,genres,test,title_genres,new_movieid,title_len
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,100,Toy Story (1995)Adventure|Animation|Children|C...,0.05,27278
1,2,Jumanji (1995),Adventure|Children|Fantasy,100,Jumanji (1995)Adventure|Children|Fantasy,0.10,27278
2,3,Grumpier Old Men (1995),Comedy|Romance,100,Grumpier Old Men (1995)Comedy|Romance,0.15,27278
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,100,Waiting to Exhale (1995)Comedy|Drama|Romance,0.20,27278
4,5,Father of the Bride Part II (1995),Comedy,100,Father of the Bride Part II (1995)Comedy,0.25,27278
...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,100,Kein Bund für's Leben (2007)Comedy,6562.70,27278
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,100,"Feuer, Eis & Dosenbier (2002)Comedy",6562.80,27278
27275,131258,The Pirates (2014),Adventure,100,The Pirates (2014)Adventure,6562.90,27278
27276,131260,Rentun Ruusu (2001),(no genres listed),100,Rentun Ruusu (2001)(no genres listed),6563.00,27278
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,100,Innocence (2014)Adventure|Fantasy|Horror,6563.10,27278

In [41]:
def sqr(r):
    return len(r)

In [44]:
df22['new_genres']=df22['genres'].map(sqr)
df22

,movieId,title,genres,test,title_genres,new_movieid,title_len,new_genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,100,Toy Story (1995)Adventure|Animation|Children|C...,0.05,27278,43
1,2,Jumanji (1995),Adventure|Children|Fantasy,100,Jumanji (1995)Adventure|Children|Fantasy,0.10,27278,26
2,3,Grumpier Old Men (1995),Comedy|Romance,100,Grumpier Old Men (1995)Comedy|Romance,0.15,27278,14
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,100,Waiting to Exhale (1995)Comedy|Drama|Romance,0.20,27278,20
4,5,Father of the Bride Part II (1995),Comedy,100,Father of the Bride Part II (1995)Comedy,0.25,27278,6
...,...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,100,Kein Bund für's Leben (2007)Comedy,6562.70,27278,6
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,100,"Feuer, Eis & Dosenbier (2002)Comedy",6562.80,27278,6
27275,131258,The Pirates (2014),Adventure,100,The Pirates (2014)Adventure,6562.90,27278,9
27276,131260,Rentun Ruusu (2001),(no genres listed),100,Rentun Ruusu (2001)(no genres listed),6563.00,27278,18
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,100,Innocence (2014)Adventure|Fantasy|Horror,6563.10,27278,24

In [45]:
len('Adventure|Fantasy|Horror')

24

In [48]:

df22['new_genres'].value_counts()

5     4572
6     3159
11    2402
13    2097
12    1900
14    1817
20    1358
15    1051
21     971
22     832
18     749
23     592
9      576
16     571
19     481
7      408
28     360
24     349
17     332
8      292
29     275
25     257
26     252
27     239
30     208
31     183
32     121
35     110
36      95
33      87
34      77
10      63
37      61
38      55
39      47
40      43
43      35
41      33
42      33
3       32
44      15
47      15
50      13
51      10
48       8
45       7
49       7
46       6
54       5
52       4
60       3
57       2
55       2
59       1
56       1
4        1
62       1
65       1
77       1
Name: new_genres, dtype: int64

In [50]:
df22['genres'].value_counts()

Drama                                                  4520
Comedy                                                 2294
Documentary                                            1942
Comedy|Drama                                           1264
Drama|Romance                                          1075
                                                       ...
Action|Comedy|Crime|Western                               1
Action|Fantasy|Sci-Fi|Thriller                            1
Action|Drama|Fantasy|Horror|Mystery|Sci-Fi|Thriller       1
Action|Drama|Fantasy|Romance                              1
Animation|Children|Comedy|Western                         1
Name: genres, Length: 1342, dtype: int64

In [52]:
[f for f in df22['genres'] if len(f)==5]

['Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Crime',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 'Drama',
 ...]

In [53]:
len([f for f in df22['genres'] if len(f)==5])

4572

In [ ]:
# find col_value count @ individual level

In [54]:
df22 ['new_t1_genres']= df22['genres'].map(lambda x:len(x))
df22

,movieId,title,genres,test,title_genres,new_movieid,title_len,new_genres,new_t1_genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,100,Toy Story (1995)Adventure|Animation|Children|C...,0.05,27278,43,43
1,2,Jumanji (1995),Adventure|Children|Fantasy,100,Jumanji (1995)Adventure|Children|Fantasy,0.10,27278,26,26
2,3,Grumpier Old Men (1995),Comedy|Romance,100,Grumpier Old Men (1995)Comedy|Romance,0.15,27278,14,14
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,100,Waiting to Exhale (1995)Comedy|Drama|Romance,0.20,27278,20,20
4,5,Father of the Bride Part II (1995),Comedy,100,Father of the Bride Part II (1995)Comedy,0.25,27278,6,6
...,...,...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,100,Kein Bund für's Leben (2007)Comedy,6562.70,27278,6,6
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,100,"Feuer, Eis & Dosenbier (2002)Comedy",6562.80,27278,6,6
27275,131258,The Pirates (2014),Adventure,100,The Pirates (2014)Adventure,6562.90,27278,9,9
27276,131260,Rentun Ruusu (2001),(no genres listed),100,Rentun Ruusu (2001)(no genres listed),6563.00,27278,18,18
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,100,Innocence (2014)Adventure|Fantasy|Horror,6563.10,27278,24,24

In [ ]:
# first few rows  -------> df.head()

In [56]:
df22.head()

,movieId,title,genres,test,title_genres,new_movieid,title_len,new_genres,new_t1_genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,100,Toy Story (1995)Adventure|Animation|Children|C...,0.05,27278,43,43
1,2,Jumanji (1995),Adventure|Children|Fantasy,100,Jumanji (1995)Adventure|Children|Fantasy,0.10,27278,26,26
2,3,Grumpier Old Men (1995),Comedy|Romance,100,Grumpier Old Men (1995)Comedy|Romance,0.15,27278,14,14
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,100,Waiting to Exhale (1995)Comedy|Drama|Romance,0.20,27278,20,20
4,5,Father of the Bride Part II (1995),Comedy,100,Father of the Bride Part II (1995)Comedy,0.25,27278,6,6

In [57]:
df22.tail()

,movieId,title,genres,test,title_genres,new_movieid,title_len,new_genres,new_t1_genres
27273,131254,Kein Bund für's Leben (2007),Comedy,100,Kein Bund für's Leben (2007)Comedy,6562.7,27278,6,6
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,100,"Feuer, Eis & Dosenbier (2002)Comedy",6562.8,27278,6,6
27275,131258,The Pirates (2014),Adventure,100,The Pirates (2014)Adventure,6562.9,27278,9,9
27276,131260,Rentun Ruusu (2001),(no genres listed),100,Rentun Ruusu (2001)(no genres listed),6563.0,27278,18,18
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,100,Innocence (2014)Adventure|Fantasy|Horror,6563.1,27278,24,24

In [58]:
 df22.head(10)

,movieId,title,genres,test,title_genres,new_movieid,title_len,new_genres,new_t1_genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,100,Toy Story (1995)Adventure|Animation|Children|C...,0.05,27278,43,43
1,2,Jumanji (1995),Adventure|Children|Fantasy,100,Jumanji (1995)Adventure|Children|Fantasy,0.10,27278,26,26
2,3,Grumpier Old Men (1995),Comedy|Romance,100,Grumpier Old Men (1995)Comedy|Romance,0.15,27278,14,14
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,100,Waiting to Exhale (1995)Comedy|Drama|Romance,0.20,27278,20,20
4,5,Father of the Bride Part II (1995),Comedy,100,Father of the Bride Part II (1995)Comedy,0.25,27278,6,6
5,6,Heat (1995),Action|Crime|Thriller,100,Heat (1995)Action|Crime|Thriller,0.30,27278,21,21
6,7,Sabrina (1995),Comedy|Romance,100,Sabrina (1995)Comedy|Romance,0.35,27278,14,14
7,8,Tom and Huck (1995),Adventure|Children,100,Tom and Huck (1995)Adventure|Children,0.40,27278,18,18
8,9,Sudden Death (1995),Action,100,Sudden Death (1995)Action,0.45,27278,6,6
9,10,GoldenEye (1995),Action|Adventure|Thriller,100,GoldenEye (1995)Action|Adventure|Thriller,0.50,27278,25,25

In [61]:
df22.isnull().sum()

movieId          0
title            0
genres           0
test             0
title_genres     0
new_movieid      0
title_len        0
new_genres       0
new_t1_genres    0
dtype: int64

In [63]:
df22.notnull().sum()

movieId          27278
title            27278
genres           27278
test             27278
title_genres     27278
new_movieid      27278
title_len        27278
new_genres       27278
new_t1_genres    27278
dtype: int64

In [64]:
type(df22['test'])

pandas.core.series.Series

In [65]:
df22['genres']= df22['genres'].map(lambda x:str(x)[:1])

In [66]:
df22

,movieId,title,genres,test,title_genres,new_movieid,title_len,new_genres,new_t1_genres
0,1,Toy Story (1995),A,100,Toy Story (1995)Adventure|Animation|Children|C...,0.05,27278,43,43
1,2,Jumanji (1995),A,100,Jumanji (1995)Adventure|Children|Fantasy,0.10,27278,26,26
2,3,Grumpier Old Men (1995),C,100,Grumpier Old Men (1995)Comedy|Romance,0.15,27278,14,14
3,4,Waiting to Exhale (1995),C,100,Waiting to Exhale (1995)Comedy|Drama|Romance,0.20,27278,20,20
4,5,Father of the Bride Part II (1995),C,100,Father of the Bride Part II (1995)Comedy,0.25,27278,6,6
...,...,...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),C,100,Kein Bund für's Leben (2007)Comedy,6562.70,27278,6,6
27274,131256,"Feuer, Eis & Dosenbier (2002)",C,100,"Feuer, Eis & Dosenbier (2002)Comedy",6562.80,27278,6,6
27275,131258,The Pirates (2014),A,100,The Pirates (2014)Adventure,6562.90,27278,9,9
27276,131260,Rentun Ruusu (2001),(,100,Rentun Ruusu (2001)(no genres listed),6563.00,27278,18,18
27277,131262,Innocence (2014),A,100,Innocence (2014)Adventure|Fantasy|Horror,6563.10,27278,24,24

# filling null values

In [71]:
 df22.fillna(0,inplace=True)
df22

,movieId,title,genres,test,title_genres,new_movieid,title_len,new_genres,new_t1_genres
0,1,Toy Story (1995),A,100,Toy Story (1995)Adventure|Animation|Children|C...,0.05,27278,43,43
1,2,Jumanji (1995),A,100,Jumanji (1995)Adventure|Children|Fantasy,0.10,27278,26,26
2,3,Grumpier Old Men (1995),C,100,Grumpier Old Men (1995)Comedy|Romance,0.15,27278,14,14
3,4,Waiting to Exhale (1995),C,100,Waiting to Exhale (1995)Comedy|Drama|Romance,0.20,27278,20,20
4,5,Father of the Bride Part II (1995),C,100,Father of the Bride Part II (1995)Comedy,0.25,27278,6,6
...,...,...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),C,100,Kein Bund für's Leben (2007)Comedy,6562.70,27278,6,6
27274,131256,"Feuer, Eis & Dosenbier (2002)",C,100,"Feuer, Eis & Dosenbier (2002)Comedy",6562.80,27278,6,6
27275,131258,The Pirates (2014),A,100,The Pirates (2014)Adventure,6562.90,27278,9,9
27276,131260,Rentun Ruusu (2001),(,100,Rentun Ruusu (2001)(no genres listed),6563.00,27278,18,18
27277,131262,Innocence (2014),A,100,Innocence (2014)Adventure|Fantasy|Horror,6563.10,27278,24,24

In [72]:
df22.isnull().sum().to_dict()

{'movieId': 0,
 'title': 0,
 'genres': 0,
 'test': 0,
 'title_genres': 0,
 'new_movieid': 0,
 'title_len': 0,
 'new_genres': 0,
 'new_t1_genres': 0}

In [73]:
# to store null values as your required place in particular col

In [76]:
df22['genres'] = df22['genres'].fillna(10)
df22 # HERE NO NULL THATS why in table thier is no change appear

,movieId,title,genres,test,title_genres,new_movieid,title_len,new_genres,new_t1_genres
0,1,Toy Story (1995),A,100,Toy Story (1995)Adventure|Animation|Children|C...,0.05,27278,43,43
1,2,Jumanji (1995),A,100,Jumanji (1995)Adventure|Children|Fantasy,0.10,27278,26,26
2,3,Grumpier Old Men (1995),C,100,Grumpier Old Men (1995)Comedy|Romance,0.15,27278,14,14
3,4,Waiting to Exhale (1995),C,100,Waiting to Exhale (1995)Comedy|Drama|Romance,0.20,27278,20,20
4,5,Father of the Bride Part II (1995),C,100,Father of the Bride Part II (1995)Comedy,0.25,27278,6,6
...,...,...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),C,100,Kein Bund für's Leben (2007)Comedy,6562.70,27278,6,6
27274,131256,"Feuer, Eis & Dosenbier (2002)",C,100,"Feuer, Eis & Dosenbier (2002)Comedy",6562.80,27278,6,6
27275,131258,The Pirates (2014),A,100,The Pirates (2014)Adventure,6562.90,27278,9,9
27276,131260,Rentun Ruusu (2001),(,100,Rentun Ruusu (2001)(no genres listed),6563.00,27278,18,18
27277,131262,Innocence (2014),A,100,Innocence (2014)Adventure|Fantasy|Horror,6563.10,27278,24,24

In [77]:
df22.fillna(100)

,movieId,title,genres,test,title_genres,new_movieid,title_len,new_genres,new_t1_genres
0,1,Toy Story (1995),A,100,Toy Story (1995)Adventure|Animation|Children|C...,0.05,27278,43,43
1,2,Jumanji (1995),A,100,Jumanji (1995)Adventure|Children|Fantasy,0.10,27278,26,26
2,3,Grumpier Old Men (1995),C,100,Grumpier Old Men (1995)Comedy|Romance,0.15,27278,14,14
3,4,Waiting to Exhale (1995),C,100,Waiting to Exhale (1995)Comedy|Drama|Romance,0.20,27278,20,20
4,5,Father of the Bride Part II (1995),C,100,Father of the Bride Part II (1995)Comedy,0.25,27278,6,6
...,...,...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),C,100,Kein Bund für's Leben (2007)Comedy,6562.70,27278,6,6
27274,131256,"Feuer, Eis & Dosenbier (2002)",C,100,"Feuer, Eis & Dosenbier (2002)Comedy",6562.80,27278,6,6
27275,131258,The Pirates (2014),A,100,The Pirates (2014)Adventure,6562.90,27278,9,9
27276,131260,Rentun Ruusu (2001),(,100,Rentun Ruusu (2001)(no genres listed),6563.00,27278,18,18
27277,131262,Innocence (2014),A,100,Innocence (2014)Adventure|Fantasy|Horror,6563.10,27278,24,24